### ISSUE TITLE
PHP Warning: Constants already defined for ZC158/php8

### ISSUE THREAD

**Issue by torvista** [lat9/emailFor404#2]
Just trying out php 8 and am paying the price...ZC158, Xampp 8.0.1-1.
This is not reported on php 7.3.

> [03-Feb-2021 16:45:08 Europe/Madrid]
Navigation: [0][not set] [1][not set] [2][not set]
Request URI: /tienda-158/
IP address: 127.0.0.1
#1  define() called at [CATALOG/includes/auto_loaders/config.emailFor404.php:17]
#2  require(CATALOG/includes/auto_loaders/config.emailFor404.php) called at [CATALOG/includes/classes/InitSystem.php:219]
#3  Zencart/InitSystem/InitSystem->getLoadersFromFilelist() called at [CATALOG/includes/classes/InitSystem.php:171]
#4  Zencart/InitSystem/InitSystem->loadAutoLoadersFromSystem() called at [CATALOG/includes/classes/InitSystem.php:33]
#5  Zencart/InitSystem/InitSystem->loadAutoLoaders() called at [CATALOG/includes/application_top.php:248]
#6  require(CATALOG/includes/application_top.php) called at [CATALOG/index.php:25]
--> PHP Warning: Constant SEND_404_ERRORS_EMAILS_TO already defined in ...\includes\auto_loaders\config.emailFor404.php on line 17.

....and for all the subsequent constants.
I imagine there is double loading from those new InitSystem...

**Comment by lat9** [comment]
Noting that this change will be, essentially, a "52-card pickup" ... i.e. every file's changed and a language file added.
