### ISSUE TITLE
configuration constants in language file

### ISSUE THREAD

**Issue by torvista** [lat9/emailFor404#3]
```
define('SEND_404_ERRORS_EMAILS_TO', 'id@yoursite.com');     // This is the email address that the 404 emails are sent to
define('SEND_404_ERRORS_EMAIL_TO_STATUS', '1');             // Set to '1' to enable the email sending
define('SEND_404_ERRORS_EMAIL_ARCHIVE', '0');               // Set to '0' for no archiving, any other value to write to email_archive in database
```
nitpick>..I would have expected these to be "elsewhere" and unique: since they get duplicated when in a language file...</nitpick

**Comment by lat9** [comment]
It's a 'simple' plugin so I didn't feel that it was necessary to make database configuration settings.  How is it that the settings get duplicated in a language file, since only one language at a time is loaded.

**Comment by torvista** [comment]
I meant duplicated in the sense that the same settings are in two places.
